cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update/<int:item_id>/', views.update_cart, name='update_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('logout/', views.user_logout, name='user_logout'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.create_order, name='create_order'),
    path('initialize_payment/<int:order_id>/', views.initialize_payment, name='initialize_payment'),
    path('payment_callback/', views.payment_callback, name='payment_callback'),
    path('webhook/', views.paystack_webhook, name='paystack_webhook'),
    path('success/<int:order_id>/', views.order_success, name='order_success'),
    path('buy_now/<int:product_id>/', views.buy_now, name='buy_now'),
]

pxomymart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),  
    path('cart/', include('cart.urls')),  
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls', namespace='orders')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.conf import settings
from django.db import models
from products.models import Product  # Adjust the import based on your project structure

class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Cart of {self.user.username}"

    def get_total_price(self):
        return sum(item.get_total_price() for item in self.items.all())

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.product.name}"

    def get_total_price(self):
        return self.product.price * self.quantity

cart/forms.py
from django import forms

class AdditionalOrderInfoForm(forms.Form):
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    state = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    lga = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    city = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    postal_code = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
    house_address = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))
    additional_info = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4}), required=False)

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.urls import reverse
from products.models import Product, Category
from .forms import AdditionalOrderInfoForm
from orders.views import create_order
from .models import Cart, CartItem
from core.models import SiteSettings
from accounts.models import Profile

@login_required
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
    if not created:
        cart_item.quantity += 1
        cart_item.save()
    return redirect('cart_detail')

@login_required
def remove_from_cart(request, item_id):
    cart_item = get_object_or_404(CartItem, id=item_id, cart__user=request.user)
    cart_item.delete()
    return redirect('cart_detail')

@login_required
def update_cart(request, item_id):
    cart_item = get_object_or_404(CartItem, id=item_id, cart__user=request.user)
    if request.method == 'POST':
        quantity = request.POST.get('quantity')
        cart_item.quantity = int(quantity)
        cart_item.save()
    return redirect('cart_detail')

@login_required
def cart_detail(request):
    user = request.user
    products = Product.objects.all()
    try:
        profile = Profile.objects.get(user=user)
    except Profile.DoesNotExist:
        profile = Profile(user=user) 

    site_settings = SiteSettings.objects.first()
    cart, created = Cart.objects.get_or_create(user=request.user)
    total_price = cart.get_total_price()
    categories = Category.objects.all()
    return render(request, 'cart/cart_detail.html', {
        'products': products,
        'cart': cart, 
        'profile': profile, 
        'total_price': total_price,
        'categories': categories,
        'site_settings': site_settings,
        })

def user_logout(request):
    logout(request)
    return redirect(reverse('login'))

@login_required
def checkout(request):
    cart = Cart.objects.get(user=request.user)
    site_settings = SiteSettings.objects.first()
    user = request.user
    profile = Profile.objects.get(user=user)
    if request.method == 'POST':
        form = AdditionalOrderInfoForm(request.POST)
        if form.is_valid():
            # If form is valid, proceed to create the order
            return create_order(request, form.cleaned_data)
    else:
        form = AdditionalOrderInfoForm()

    return render(request, 'cart/checkout.html', {
        'cart': cart,
        'site_settings': site_settings,
        'form': form,
        'profile': profile,
    })

cart/templates/cart/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% if site_settings.title %}{{ site_settings.title }}{% else %}My Site{% endif %} | {% block title %} {% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% if site_settings.favicon %}{{ site_settings.favicon.url }}{% endif %}" rel="icon">
  <link href="{% if site_settings.favicon %}{{ site_settings.favicon.url }}{% endif %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'assets/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'assets/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/simple-datatables/style.css' %}" rel="stylesheet">
  <!-- MDB -->
  <link rel="stylesheet" href="{% static 'assets/MDB5/css/mdb.min.css' %}" />

  

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/dashboard-style.css' %}" rel="stylesheet">
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url "index" %}" class="logo d-flex align-items-center">
        {% if site_settings.logo %}
          <img src="{{ site_settings.logo.url }}"  alt="">
          <span class="d-none d-lg-block">ProxyMart</span>
        {% else %}
          <img src="{% static 'assets/images/p-m-logoT.PNG' %}" alt="Logo" width="200" height="50" class="d-inline-block align-text-top">
        {% endif %}
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="{% url 'cart_detail' %}">
            <i class="bi bi-cart4"></i>
            <span class="badge bg-success badge-number">{{ cart_item_count }}</span>
          </a><!-- End Messages Icon -->

        </li><!-- End Messages Nav -->

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            {% if profile.image %}
              <img src="{{ profile.image.url }}" alt="Profile" class="rounded-circle">
            {% else %}
              <img src="{% static 'assets/images/download.PNG' %}" alt="Profile" class="rounded-circle">
            {% endif %}
            <span class="d-none d-md-block dropdown-toggle ps-2">{{ profile.user.username }}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{ profile.user.username }}</h6>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'profile' %}">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            {% if user.is_authenticated %}
              <li>
                <a class="dropdown-item d-flex align-items-center" href="{% url 'user_logout' %}">
                  <i class="bi bi-box-arrow-right"></i>
                  <span>Sign Out</span>
                </a>
              </li>
            {% endif %}

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="{% url 'home' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'profile' %}">
          <i class="bi bi-person"></i>
          <span>Profile</span>
        </a>
      </li><!-- End Profile Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'orders_history' %}">
          <i class="bi bi-card-list"></i>
          <span>Order History</span>
        </a>
      </li><!-- End F.A.Q Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'transaction_history' %}">
          <i class="bi bi-cash-coin"></i>
          <span>Transaction History</span>
        </a>
      </li><!-- End F.A.Q Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'cart_detail' %}">
          <i class="bi bi-envelope"></i>
          <span>Cart Items</span>
        </a>
      </li><!-- End Contact Page Nav -->

    </ul>

  </aside><!-- End Sidebar-->

  <main id="main" class="main">
        {% block content %}
       

        {% endblock %}
   
  </main><!-- End #main -->
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
   <div class="copyright">
     &copy; Copyright <strong><span>PROXYMART</span></strong>. All Rights Reserved
   </div>
   <div class="credits">
    
     Designed by <a href="#">Mr Nova</a>
   </div>
 </footer><!-- End Footer -->
 
 <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
 
 <!-- Vendor JS Files -->
 <script src="{% static 'assets/apexcharts/apexcharts.min.js' %}"></script>
 <script src="{% static 'assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
 <script src="{% static 'assets/chart.js/chart.umd.js' %}"></script>
 <script src="{% static 'assets/echarts/echarts.min.js' %}"></script>
 <script src="{% static 'assets/quill/quill.js' %}"></script>
 <script src="{% static 'assets/simple-datatables/simple-datatables.js' %}"></script>
 <script src="{% static 'assets/tinymce/tinymce.min.js' %}"></script>
 <script src="{% static 'assets/php-email-form/validate.js' %}"></script>

 <!-- MDB -->
 <script type="text/javascript" src="{% static 'assets/MDB5/js/mdb.umd.min.js' %}"></script>
 
 <!-- Template Main JS File -->
 <script src="{% static 'assets/js/dashboard-main.js' %}"></script>
 
 </body>
 
 </html>

cart/templates/cart/checkout.html
{% extends 'cart/base.html' %}
{% load static %}
{% block title %} Checkout {% endblock %}
{% block content %}
      <section class=" py-5">
        <div class="container">
          <div class="row">

            <div class="col-xl-8 col-lg-8 mb-4">
      
              <!-- Checkout -->
              <div class="card shadow-0 border">

                <div class="p-4">
                    <h4 class="mb-3">Checkout Summary</h4>
                    <div class="d-flex justify-content-between">
                    <p class="mb-2">Total price:</p>
                    <p class="mb-2">#{{ cart.get_total_price }}</p>
                    </div>
                    <div class="d-flex justify-content-between">
                    <p class="mb-2">Shipping cost:</p>
                    <p class="mb-2">+ $14.00</p>
                    </div>
                    <hr />
                    <div class="d-flex justify-content-between">
                    <p class="mb-2">Total price:</p>
                    <p class="mb-2 fw-bold">#{{ cart.get_total_price }}</p>
                    </div>
                    <hr />
                </div>

                <div class="p-4">

                  <!-- In checkout.html template -->
                  <form method="post" action="{% url 'orders:create_order' %}">
                    {% csrf_token %}
                    
                    <div class="mb-3">
                        <label for="use_default_shipping">
                            <input type="checkbox" id="use_default_shipping" name="use_default_shipping" value="1">
                            Use default shipping information
                        </label>
                    </div>

                    <div id="hidden-element" class="row border rounded-3 mb-3" style="display: none;">
                        <div class="row">
                            <div class="col-lg-4 mb-3">
                                <div class="p-3 h-100">
                                  <label class="form-check-label" for="flexRadioDefault1">
                                    State <br />
                                    <small class="text-muted">{{ profile.state }} </small>
                                  </label>
                                </div>
                            </div>
                            <div class="col-lg-4 mb-3">
                                <div class="p-3 h-100">
                                  <label class="form-check-label" for="flexRadioDefault1">
                                    City <br />
                                    <small class="text-muted">{{ profile.city }} </small>
                                  </label>
                                </div>
                            </div>
                            <div class="col-lg-4 mb-3">
                                <div class="p-3 h-100">
                                  <label class="form-check-label" for="flexRadioDefault1">
                                    LGA <br />
                                    <small class="text-muted">{{ profile.lga }} </small>
                                  </label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4 mb-3">
                                <div class="p-3 h-100">
                                  <label class="form-check-label" for="flexRadioDefault1">
                                    Town <br />
                                    <small class="text-muted">{{ profile.town }} </small>
                                  </label>
                                </div>
                            </div>
                            <div class="col-lg-4 mb-3">
                                <div class="p-3 h-100">
                                  <label class="form-check-label" for="flexRadioDefault1">
                                    Zipcode <br />
                                    <small class="text-muted">{{ profile.zipcode }} </small>
                                  </label>
                                </div>
                            </div>
                            <div class="col-lg-4 mb-3">
                                <div class="p-3 h-100">
                                  <label class="form-check-label" for="flexRadioDefault1">
                                    Street <br />
                                    <small class="text-muted">{{ profile.street }} </small>
                                  </label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4 mb-3">
                                <div class="p-3 h-100">
                                  <label class="form-check-label" for="flexRadioDefault1">
                                    House Address <br />
                                    <small class="text-muted">{{ profile.house_address }} </small>
                                  </label>
                                </div>
                            </div>
                            <div class="col-lg-4 mb-3">
                                <div class="p-3 h-100">
                                  <label class="form-check-label" for="flexRadioDefault1">
                                    Mobile number <br />
                                    <small class="text-muted">{{ profile.mobile_number }} </small>
                                  </label>
                                </div>
                            </div>
                            <div class="col-lg-4 mb-3">
                                <div class="p-3 h-100">
                                  <label class="form-check-label" for="flexRadioDefault1">
                                    Additional Info <br />
                                    <small class="text-muted">{{ profile.additional_info }} </small>
                                  </label>
                                </div>
                            </div>
                        </div>
                        <div class="text-center">
                            <a href="{% url 'profile' %}" class="btn btn-primary shadow-primary border text-light my-3">Edit Shipping Info</a>
                        </div>
                    </div>
                    
                    <div id="additional-info-form">
                        <div class="row">
                            <div class="form-group col-6 mb-3">
                                <label for="{{ form.first_name.id_for_label }}">First Name:</label>
                                {{ form.first_name }}
                            </div>
                            <div class="form-group col-6 mb-3">
                                <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-6 mb-3">
                                <label for="{{ form.phone_number.id_for_label }}">Phone Number:</label>
                                {{ form.phone_number }}
                            </div>
                            <div class="form-group col-6 mb-3">
                                <label for="{{ form.email.id_for_label }}">Email:</label>
                                {{ form.email }}
                            </div>
                        </div>
                        <hr class="my-4" />
                
                        <h4 class="card-title mb-3">Shipping info</h4>
                        
                        <div class="row">
                            <div class="form-group col-6 mb-3">
                                <label for="{{ form.state.id_for_label }}">State:</label>
                                {{ form.state }}
                            </div>
                            <div class="form-group col-6 mb-3">
                                <label for="{{ form.lga.id_for_label }}">LGA:</label>
                                {{ form.lga }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-6 mb-3">
                                <label for="{{ form.city.id_for_label }}">City:</label>
                                {{ form.city }}
                            </div>
                            <div class="form-group col-6 mb-3">
                                <label for="{{ form.postal_code.id_for_label }}">Postal Code:</label>
                                {{ form.postal_code }}
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <label for="{{ form.house_address.id_for_label }}">House Address:</label>
                            {{ form.house_address }}
                        </div>
                        <div class="form-group mb-3">
                            <label for="{{ form.additional_info.id_for_label }}">Additional Info:</label>
                            {{ form.additional_info }}
                        </div>
                    </div>
                    
                    <a href="{% url 'cart_detail' %}" class="btn btn-light shadow-0 border border-danger">Cancel</a>
                    <button type="submit" class="btn btn-success shadow-0 border">Proceed to Payment</button>
                  </form>
                
                  <script>
                    document.addEventListener('DOMContentLoaded', function() {
                      const checkbox = document.getElementById('use_default_shipping');
                      const formDiv = document.getElementById('additional-info-form');
                      const formFields = formDiv.querySelectorAll('input, textarea');
                      const hiddenElement = document.getElementById('hidden-element'); // Add this line
                  
                      checkbox.addEventListener('change', function() {
                        if (this.checked) {
                          formDiv.style.display = 'none';
                          formFields.forEach(field => {
                            field.disabled = true;
                          });
                          hiddenElement.style.display = 'block'; // Add this line
                        } else {
                          formDiv.style.display = 'block';
                          formFields.forEach(field => {
                            field.disabled = false;
                          });
                          hiddenElement.style.display = 'none'; // Add this line
                        }
                      });
                  
                      // Initial check to disable the form if the checkbox is already checked
                      if (checkbox.checked) {
                        formDiv.style.display = 'none';
                        formFields.forEach(field => {
                          field.disabled = true;
                        });
                        hiddenElement.style.display = 'block'; // Add this line
                      }
                    });
                  </script>
                  
                
                  
                </div>
              </div>
              <!-- Checkout -->
            </div>
            <div class="col-xl-4 col-lg-4 d-flex justify-content-center justify-content-lg-end">
                <div class="ms-lg-4 mt-4 mt-lg-0 p-3" style="max-width: 320px; max-height: 900px; overflow-y: scroll;">
                    
                  <h4 class="text-dark my-4">Items in cart</h4>
                    
                  {% for item in cart.items.all %}
                    <div class="d-flex align-items-center mb-4">
                        <div class="me-3 position-relative">
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill badge-secondary">
                            {{ item.quantity }}
                        </span>
                        <img src="{{ item.product.images.url }}" style="height: 96px; width: 96px;" class="img-sm rounded border" />
                        </div>
                        <div class="">
                        <a href="#" class="nav-link">
                            {{ item.product.name }}
                        </a>
                        <div class="price text-muted">Total: #{{ item.get_total_price }}</div>
                        </div>
                    </div>
                  {% endfor %}

                </div>
            </div>
          </div>
        </div>
      </section>
      

      
{% endblock %}