cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update/<int:item_id>/', views.update_cart, name='update_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('logout/', views.user_logout, name='user_logout'),
]

core/urls.py
from django.urls import path
from .views import index, user_logout

urlpatterns = [
    path('', index, name='index'),
    path('logout/', user_logout, name='user_logout'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.create_order, name='create_order'),
    path('initialize_payment/<int:order_id>/', views.initialize_payment, name='initialize_payment'),
    path('payment_callback/', views.payment_callback, name='payment_callback'),
    path('webhook/', views.paystack_webhook, name='paystack_webhook'),
    path('success/<int:order_id>/', views.order_success, name='order_success'),
    path('buy_now/<int:product_id>/', views.buy_now, name='buy_now'),
]

pxomymart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),  
    path('cart/', include('cart.urls')),  
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls', namespace='orders')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

class Slider(models.Model):
    topic = models.CharField(max_length=255, verbose_name="Topic")
    description = models.TextField(blank=True, null=True, verbose_name="Description")
    button_text = models.CharField(max_length=50, blank=True, null=True, verbose_name="Button Text")
    button_url = models.URLField(blank=True, null=True, verbose_name="Button URL")

    def __str__(self):
        return self.topic

    class Meta:
        verbose_name = "Slider"
        verbose_name_plural = "Sliders"

class SiteSettings(models.Model):
    title = models.CharField(max_length=255, verbose_name="Site Title")
    site_name = models.CharField(max_length=255, verbose_name="Site Name")
    description = models.TextField(blank=True, null=True, verbose_name="Description")
    favicon = models.ImageField(upload_to='images/favicons/', blank=True, null=True, verbose_name="Favicon")
    logo = models.ImageField(upload_to='images/logos/', blank=True, null=True, verbose_name="Logo")
    banner_img = models.ImageField(upload_to='images/banner', verbose_name="Banner Image")
    footer_text = models.TextField(blank=True, null=True, verbose_name="Footer Text")
    contact_email = models.EmailField(blank=True, null=True, verbose_name="Contact Email")
    sliders = models.ManyToManyField(Slider, blank=True, verbose_name="Slider Content")

    def __str__(self):
        return self.site_name

    class Meta:
        verbose_name = "Site Setting"
        verbose_name_plural = "Site Settings"

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.urls import reverse
from .models import SiteSettings
from products.models import Category, Product

# Create your views here.

def index(request):
    site_settings = SiteSettings.objects.first()
    categories = Category.objects.all()
    products = Product.objects.all().order_by('?')
    user = request.user
    username = user.username
    
    
    context = {
        'site_settings': site_settings,
        'categories': categories,
        'products': products,
        'user': user,
        'username': username,
    }
    return render(request, 'core/index.html', context)

def user_logout(request):
    logout(request)
    return redirect(reverse('login'))

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
    {% load static %}
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>{% if site_settings.title %}{{ site_settings.title }}{% else %}My Site{% endif %} | {% block title %} {% endblock %} </title>
      <meta name="keywords" content="">
      <meta name="description" content="{% if site_settings.description %}{{ site_settings.description }}{% endif %}">
      <meta name="author" content="Mr Nova">

      <meta property="og:title" content="{% if site_settings.title %}{{ site_settings.title }}{% else %}My Site{% endif %}">
      <meta property="og:description" content="{% if site_settings.description %}{{ site_settings.description }}{% endif %}">
      <meta property="og:image" content="{% if site_settings.banner_img %}{{ site_settings.banner_img.url }}{% endif %}">
      <meta property="og:url" content="#">
      <meta property="og:type" content="website">
      <!-- bootstrap css -->
      <link rel="stylesheet" type="text/css" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% if site_settings.favicon %}{{ site_settings.favicon.url }}{% endif %}" type="image/x-icon" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'assets/css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <!-- fonts -->
      <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
      <!-- font awesome -->
      <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
      <!-- Bootstrap Fonts -->
      <link href="{% static 'assets/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
      <!-- owl stylesheets -->
      <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Poppins:400,700&display=swap&subset=latin-ext" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
      <link rel="stylesoeet" href="{% static 'assets/css/owl.theme.default.min.css' %}">
      <link rel="stylesheet" href="{% static 'assets/css/jquery.fancybox.min.css' %}" media="screen">

      <style>
         .banner_bg_main {
            width: 100%;
            float: left;
            background-image: url("{{ site_settings.banner_img.url }}");
            height: 90vh;
            background-size: 100%;
            background-repeat: no-repeat;
        }
     </style>
   </head>
   <body>
      <!-- banner bg main start -->
      <div class="banner_bg_main">
         <!-- logo section start -->
         <div class="logo_section">
            <div class="container">
               <div class="row">
                  <div class="col-sm-12">
                     {% if site_settings.logo %}
                        <a href="{% url "index" %}"><img src="{% if site_settings.logo %}{{ site_settings.logo.url }}{% endif %}" alt="Logo" width="200" height="50" alt="Logo"></a>
                     {% else %}
                        <div class="logo2"><a href="{% url "index" %}" class="audiowide-regular">Proxy<span>mart</span></a></div>
                     {% endif %}
                  </div>
               </div>
            </div>
         </div>
         <!-- logo section end -->
         <!-- header section start -->
         <div class="header_section">
            <div class="container bg-danger bg-opacity-50 rounded p-3">
               <div class="containt_main">
                  <div id="mySidenav" class="sidenav">
                     <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                     <a href="index.html">Home</a>
                     <a href="fashion.html">Fashion</a>
                     <a href="electronic.html">Electronic</a>
                     <a href="jewellery.html">Jewellery</a>
                  </div>
                  <span class="toggle_icon" onclick="openNav()"><img src="{% static 'assets/images/toggle-icon.png' %}"></span>
                  <div class="dropdown">
                     <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">All Category 
                     </button>
                     <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        {% if categories %}
                            {% for category in categories %}
                                <a class="dropdown-item" href="#">{{ category.name }}</a>
                            {% endfor %}
                        {% endif %}
                     </div>
                  </div>
                  <div class="main">
                     <!-- Another variation with a button -->
                     <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search this blog">
                        <div class="input-group-append">
                           <button class="btn btn-secondary" type="button" style="background-color: #f26522; border-color:#f26522 ">
                           <i class="bi bi-search"></i>
                           </button>
                        </div>
                     </div>
                  </div>
                  <div class="header_box">
                     <div class="lang_box ">
                        <a href="#" title="Language" class="nav-link" data-toggle="dropdown" aria-expanded="true">
                        <img src="{% static 'assets/images/flag-uk.png' %}" alt="flag" class="mr-2 " title="United Kingdom"> English <i class="bi bi-angle-down ml-2" aria-hidden="true"></i>
                        </a>
                        <div class="dropdown-menu ">
                           <a href="#" class="dropdown-item">
                           <img src="{% static 'assets/images/flag-france.png' %}" class="mr-2" alt="flag">
                           French
                           </a>
                        </div>
                     </div>
                     <div class="login_menu">
                        <ul>
                           <li><a href="{% url 'cart_detail' %}">
                              <i class="bi bi-cart4" aria-hidden="true"></i>
                              <span class="padding_10"> {{ cart_item_count }}</span>
                           </a>
                           </li>
                           {% if user.is_authenticated %}
                              <div class="dropdown">
                                 <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account
                                 </button>
                                 <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="{% url 'home' %}">Hello, {{ username }}</a>
                                    <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
                                    {% if user.is_authenticated %}
                                       <a class="dropdown-item" href="{% url 'user_logout' %}">Logout</a>
                                    {% endif %}
                                 </div>
                              </div>
                           {% else %}
                              <div class="dropdown">
                                 <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account
                                 </button>
                                 <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                                    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                                 </div>
                              </div>
                           {% endif %}
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- header section end -->
         <!-- banner section start -->
         <div class="banner_section layout_padding">
            <div class="container">
               <div id="my_slider" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                        {% for slider in site_settings.sliders.all %}
                            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                <div class="row">
                                <div class="col-sm-12 text-center">
                                    <h1 class="banner_taital">{{ slider.topic }}</h1>
                                    <p class="text-light">{{ slider.description }}</p>
                                    {% if slider.button_text and slider.button_url %}
                                        <div class="buynow_bt"><a href="{{ slider.button_url }}">{{ slider.button_text }}</a></div>
                                    {% endif %}
                                </div>
                                </div>
                            </div>
                        {% endfor %}
                  </div>
                  <a class="rounded carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                  <i class="bi bi-chevron-double-left"></i>
                  </a>
                  <a class="rounded carousel-control-next" href="#my_slider" role="button" data-slide="next">
                  <i class="bi bi-chevron-double-right"></i>
                  </a>
               </div>
            </div>
         </div>
         <!-- banner section end -->
      </div>
      <!-- banner bg main end -->

      {% block content %}
      {% endblock %}

      <!-- Scroll to top section start -->
      <button class="stt" onclick="scrollToTop()">
        <i class="bi bi-arrow-up-short"></i>
     </button>
     <!-- Scroll to top section end -->

     <!-- footer section start -->
      <div class="footer_section layout_padding">
         <div class="container text-center">
            <div class="footer_logo">
               <a href="{% url "index" %}">
                     {% if site_settings.logo %}
                        <img src="{% if site_settings.logo %}{{ site_settings.logo.url }}{% endif %}" alt="Logo" width="200" height="50" alt="Logo">
                     {% else %}
                        <img src="{% static 'assets/images/p-m-logoT.PNG' %}" alt="Logo" width="200" height="50" class="d-inline-block align-text-top">
                     {% endif %}
               </a>
            </div>
            <p>{% if site_settings.footer_text %}{{ site_settings.footer_text }}{% else %}Default footer text{% endif %}</p>
         
         </div>
      </div>
     <!-- footer section end -->
     <!-- copyright section start -->
     <div class="copyright_section">
        <div class="container">
           <p class="copyright_text">© 2024 All Rights Reserved. Design by <a href="#">Mr Nova</a></p>
        </div>
     </div>
     <!-- copyright section end -->
     <!-- Javascript files-->
     <script src="{% static 'assets/js/jquery.min.js' %}"></script>
     <script src="{% static 'assets/js/popper.min.js' %}"></script>
     <script src="{% static 'assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
     <script src="{% static 'assets/js/jquery-3.0.0.min.js' %}"></script>
     <script src="{% static 'assets/js/plugin.js' %}"></script>
     <!-- sidebar -->
     <script src="{% static 'assets/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
     <script src="{% static 'assets/js/custom.js' %}"></script>
     <script>
         /* Scroll to top
        -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- */
        function openNav() {
           document.getElementById("mySidenav").style.width = "250px";
           }
           
           function closeNav() {
           document.getElementById("mySidenav").style.width = "0";
           }

           // Show or hide the button based on scroll position
           window.onscroll = function() {
              const scrollTopButton = document.querySelector('.stt');
              if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                 scrollTopButton.style.display = 'block';
              } else {
                 scrollTopButton.style.display = 'none';
              }
           };

           // Scroll to the top of the page when the button is clicked
           function scrollToTop() {
              window.scrollTo({ top: 0, behavior: 'smooth' });
           }

     </script>
  </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %} Home {% endblock %}
{% block content %}
{% load static %}
      <!-- fashion section start -->
      <div class="fashion_section">
        <div class="container text-center">
            <h1>{% if site_settings.site_name %}{{ site_settings.site_name }}{% else %}My Site{% endif %}</h1>
            <p>
                {% if site_settings.description %}{{ site_settings.description }}{% endif %}
            </p>
        </div>
         <div id="main_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <h1 class="fashion_taital">Man & Woman Fashion</h1>
                     <div class="fashion_section_2">
                        <div class="row">
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Man T -shirt</h4>
                                 <p class="price_text">Price  <span style="color: #262626;">$ 30</span></p>
                                 <div class="tshirt_img"><img src="{% static 'assets/images/tshirt-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Man -shirt</h4>
                                 <p class="price_text">Price  <span style="color: #262626;">$ 30</span></p>
                                 <div class="tshirt_img"><img src="{% static 'assets/images/dress-shirt-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Woman Scart</h4>
                                 <p class="price_text">Price  <span style="color: #262626;">$ 30</span></p>
                                 <div class="tshirt_img"><img src="{% static 'assets/images/women-clothes-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container">
                     <h1 class="fashion_taital">Man & Woman Fashion</h1>
                     <div class="fashion_section_2">
                        <div class="row">
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Man T -shirt</h4>
                                 <p class="price_text">Price  <span style="color: #262626;">$ 30</span></p>
                                 <div class="tshirt_img"><img src="{% static 'assets/images/tshirt-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Man -shirt</h4>
                                 <p class="price_text">Price  <span style="color: #262626;">$ 30</span></p>
                                 <div class="tshirt_img"><img src="{% static 'assets/images/dress-shirt-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Woman Scart</h4>
                                 <p class="price_text">Price  <span style="color: #262626;">$ 30</span></p>
                                 <div class="tshirt_img"><img src="{% static 'assets/images/women-clothes-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container">
                     <h1 class="fashion_taital">Man & Woman Fashion</h1>
                     <div class="fashion_section_2">
                        <div class="row">
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Man T -shirt</h4>
                                 <p class="price_text">Price  <span style="color: #262626;">$ 30</span></p>
                                 <div class="tshirt_img"><img src="{% static 'assets/images/tshirt-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Man -shirt</h4>
                                 <p class="price_text">Price  <span style="color: #262626;">$ 30</span></p>
                                 <div class="tshirt_img"><img src="{% static 'assets/images/dress-shirt-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">Woman Scart</h4>
                                 <p class="price_text">Price  <span style="color: #262626;">$ 30</span></p>
                                 <div class="tshirt_img"><img src="{% static 'assets/images/women-clothes-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="#">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="#">See More</a></div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <a class="rounded carousel-control-prev" href="#main_slider" role="button" data-slide="prev">
            <i class="bi bi-chevron-double-left"></i>
            </a>
            <a class="rounded carousel-control-next" href="#main_slider" role="button" data-slide="next">
            <i class="bi bi-chevron-double-right"></i>
            </a>
         </div>
      </div>
      <!-- fashion section end -->

      
      <!-- electronic section start -->
      <div class="fashion_section">
         <div id="electronic_main_slider" class="" >
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <h1 class="fashion_taital">Electronic</h1>
                     <div class="fashion_section_2">
                        <div class="row">
                            {% for product in products %}
                                <div class="col col-lg-3 col-md-2">
                                    <div class="box_main rounded">
                                       <h4 class="shirt_text text-truncate"><a href="{% url 'product_detail' product.pk %}">{{ product.name }}</a></h4>
                                       <p class="price_text">Price <span style="color: #262626;"># {{ product.price }}</span></p>
                                       <div class="electronic_img"><img class="rounded" src="{{ product.images.url }}" alt="{{ product.name }}"></div>
                                       <p class="description_text">{{ product.description }}</p>
                                       <div class="btn_main">
                                          <div class="buy_bt"><a href="#">{{ product.quantity }} <i>left</i></a></div>
                                          <div class="buy_bt"><a href="{% url 'orders:buy_now' product.id %}">Buy Now</a></div>
                                          <div class="seemore_bt"><a href="{% url 'product_list' %}">See More</a></div>
                                       </div>
                                    </div>
                                 </div>
                            {% endfor %}
                        </div>
                     </div>
                  </div>
               </div>
            </div>   
         </div>
      </div>
      <!-- electronic section end -->
       
      <!-- jewellery  section start -->
       <div class="jewellery_section">
         <div class="loader_main">
            <div class="loader"></div>
         </div>
       </div>
      
      <!-- jewellery  section end -->

      {% endblock %}